# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {USF-XSim 62}  -string {{ERROR: [USF-XSim-62] 'compile' step failed with error(s). Please check the Tcl console output or 'C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/visualisatie.sim/sim_1/behav/xvhdl.log' file for more information.}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/Visualisatie.cache/wt [current_project]
set_property parent.project_path C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/Visualisatie.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/clk_wiz_0_clk_wiz.vhd
  C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/clk_wiz_0.vhd
  C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/Vga_control.vhd
  C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/Top.vhd
}
read_xdc C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Ben/Documents/GitHub/Fpga_project/Visualisatie/Basys3_Master.xdc]

synth_design -top Top -part xc7a35tcpg236-1
write_checkpoint -noxdef Top.dcp
catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
